name: Build
inputs:
  aws-access-key-id: 
    required: true
  aws-secret-access-key:
    required: true
  aws-account:
    required: true
  aws-region:
    required: true
  build-args:
    required: true
  ecr-repository-name:
    required: true

runs:
  using: "composite"
  shell: bash
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
        username: ${{ inputs.aws-access-key-id }}
        password: ${{ inputs.aws-secret-access-key }}
    - name: Variable declare
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::${{ env.GIT_SHA }}"
    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          ${{ inputs.build-args }}
          push: true
          tags: |
            ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository-name }}:${{ env.TAG }}
            ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository-name }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
