name: Reusable workflow example

on: 
  workflow_call:
#     inputs:
#       has-secrets:
#         required: false
#         type: boolean
#         default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.has-secret && 'aaa' || 'bbb' }} ooo
      
