name: Reusable workflow example

on: 
  workflow_dispatch:
    inputs:
      has-secrets:
        required: false
        type: boolean
        default: true

jobs:
  sss:
    runs-on: ubuntu-latest
    steps:
      - name: kkk
        run: |
          echo ${{ inputs.has-secret && 'aaa' || 'bbb' }} ooo
      
