name: Reusable workflow example

on: 
  workflow_call:
#     inputs:
#       has-secrets:
#         required: false
#         type: boolean
#         default: true

jobs:
  sss:
    runs-on: ubuntu-latest
    steps:
      - name: kkk
        run: |
          echo ooo
      
