on:
  workflow_call:
    secrets:
      aws-access-key-id: 
        required: true
      aws-secret-access-key:
        required: true
      aws-account:
        required: true
      github-secret-token:
        required: true

    inputs:
      tag:
        required: false
        type: string
        default: 'latest'
      aws-region: 
        required: false
        type: string
        default: 'eu-north-1'
      build-args:
        required: true
        type: string
      ecr-repository-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
          username: ${{ secrets.aws-access-key-id }}
          password: ${{ secrets.aws-secret-access-key }}
      - name: Variable declare
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::${{ github.sha }}"
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GITHUB_USER=strongsd-tech
            GITHUB_SECRET_TOKEN=${{ secrets.github-secret-token }}
            ${{ inputs.build-args }}
          push: true
          tags: |
            ${{ secrets.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository-name }}:${{ inputs.tag }}
            ${{ secrets.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository-name }}:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
